# Generated by Django 3.2.7 on 2021-11-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChattingMsg',
            fields=[
                ('msg_num', models.AutoField(primary_key=True, serialize=False)),
                ('writer_num', models.IntegerField()),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dr_num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('inst_num', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('center', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pt_num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('q_num', models.AutoField(primary_key=True, serialize=False)),
                ('voice_emo', models.CharField(max_length=20)),
                ('text_emo', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('depth', models.IntegerField()),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('res_num', models.AutoField(primary_key=True, serialize=False)),
                ('voice_emo', models.CharField(max_length=20)),
                ('text_emo', models.CharField(max_length=20)),
                ('msg_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.chattingmsg')),
            ],
        ),
        migrations.CreateModel(
            name='ChattingRoom',
            fields=[
                ('room_num', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('pt_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='chattingmsg',
            name='room_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.chattingroom'),
        ),
    ]
